#!/usr/bin/env bash

set -e

GO="godep go"

ORG_PATH="github.com/kelseyhightower"
REPO_PATH="${ORG_PATH}/confd"

SCRIPT=$( realpath $0 )
SCRIPTPATH=$( dirname $SCRIPT )

export GOPATH=$SCRIPTPATH/gopath
rm -f $GOPATH/src/${REPO_PATH}
mkdir -p $GOPATH/src/${ORG_PATH}
ln -s ${PWD} $GOPATH/src/${REPO_PATH}

echo "Building confd..."
# Static compilation is useful when confd is run in a container
CGO_ENABLED=0 $GO build -a -installsuffix cgo -ldflags '-s' -o bin/confd ${REPO_PATH}
