#!/usr/bin/env bash

set -e

GO="godep go"

ORG_PATH="github.com/kelseyhightower"
REPO_PATH="${ORG_PATH}/confd"

# Generating extensions
# go-extpoints resource/template/extensions

echo "Building confd..."
# Static compilation is useful when confd is run in a container
CGO_ENABLED=0 $GO build -a -installsuffix cgo -ldflags '-s' -o bin/confd ${REPO_PATH}
