#!/usr/bin/env bash

set -e

GO="godep go"

echo "Building confd..."
CONFD_ROOT=$(cd $(dirname $0); pwd)
cd ${CONFD_ROOT}/confd
# Static compilation is useful when confd is run in a container
CGO_ENABLED=0 $GO build -a -installsuffix cgo -ldflags '-s' -o ${CONFD_ROOT}/bin/confd
