// Code generated by protoc-gen-go. DO NOT EDIT.
// source: database.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	database.proto

It has these top-level messages:
	ConfigureRequest
	ConfigureResponse
	GetValuesRequest
	GetValuesResponse
	WatchPrefixRequest
	WatchPrefixResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type ConfigureRequest struct {
	Config map[string]string `protobuf:"bytes,1,rep,name=config" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ConfigureRequest) Reset()                    { *m = ConfigureRequest{} }
func (m *ConfigureRequest) String() string            { return proto1.CompactTextString(m) }
func (*ConfigureRequest) ProtoMessage()               {}
func (*ConfigureRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ConfigureRequest) GetConfig() map[string]string {
	if m != nil {
		return m.Config
	}
	return nil
}

type ConfigureResponse struct {
}

func (m *ConfigureResponse) Reset()                    { *m = ConfigureResponse{} }
func (m *ConfigureResponse) String() string            { return proto1.CompactTextString(m) }
func (*ConfigureResponse) ProtoMessage()               {}
func (*ConfigureResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetValuesRequest struct {
	Keys []string `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty"`
}

func (m *GetValuesRequest) Reset()                    { *m = GetValuesRequest{} }
func (m *GetValuesRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetValuesRequest) ProtoMessage()               {}
func (*GetValuesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetValuesRequest) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type GetValuesResponse struct {
	Values map[string]string `protobuf:"bytes,1,rep,name=values" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *GetValuesResponse) Reset()                    { *m = GetValuesResponse{} }
func (m *GetValuesResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetValuesResponse) ProtoMessage()               {}
func (*GetValuesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetValuesResponse) GetValues() map[string]string {
	if m != nil {
		return m.Values
	}
	return nil
}

type WatchPrefixRequest struct {
	Prefix    string   `protobuf:"bytes,1,opt,name=prefix" json:"prefix,omitempty"`
	Keys      []string `protobuf:"bytes,2,rep,name=keys" json:"keys,omitempty"`
	WaitIndex uint64   `protobuf:"varint,3,opt,name=wait_index,json=waitIndex" json:"wait_index,omitempty"`
}

func (m *WatchPrefixRequest) Reset()                    { *m = WatchPrefixRequest{} }
func (m *WatchPrefixRequest) String() string            { return proto1.CompactTextString(m) }
func (*WatchPrefixRequest) ProtoMessage()               {}
func (*WatchPrefixRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *WatchPrefixRequest) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *WatchPrefixRequest) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *WatchPrefixRequest) GetWaitIndex() uint64 {
	if m != nil {
		return m.WaitIndex
	}
	return 0
}

type WatchPrefixResponse struct {
	Index uint64 `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
}

func (m *WatchPrefixResponse) Reset()                    { *m = WatchPrefixResponse{} }
func (m *WatchPrefixResponse) String() string            { return proto1.CompactTextString(m) }
func (*WatchPrefixResponse) ProtoMessage()               {}
func (*WatchPrefixResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *WatchPrefixResponse) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func init() {
	proto1.RegisterType((*ConfigureRequest)(nil), "proto.ConfigureRequest")
	proto1.RegisterType((*ConfigureResponse)(nil), "proto.ConfigureResponse")
	proto1.RegisterType((*GetValuesRequest)(nil), "proto.GetValuesRequest")
	proto1.RegisterType((*GetValuesResponse)(nil), "proto.GetValuesResponse")
	proto1.RegisterType((*WatchPrefixRequest)(nil), "proto.WatchPrefixRequest")
	proto1.RegisterType((*WatchPrefixResponse)(nil), "proto.WatchPrefixResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Database service

type DatabaseClient interface {
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	GetValues(ctx context.Context, in *GetValuesRequest, opts ...grpc.CallOption) (*GetValuesResponse, error)
	WatchPrefix(ctx context.Context, in *WatchPrefixRequest, opts ...grpc.CallOption) (*WatchPrefixResponse, error)
}

type databaseClient struct {
	cc *grpc.ClientConn
}

func NewDatabaseClient(cc *grpc.ClientConn) DatabaseClient {
	return &databaseClient{cc}
}

func (c *databaseClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	out := new(ConfigureResponse)
	err := grpc.Invoke(ctx, "/proto.Database/Configure", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) GetValues(ctx context.Context, in *GetValuesRequest, opts ...grpc.CallOption) (*GetValuesResponse, error) {
	out := new(GetValuesResponse)
	err := grpc.Invoke(ctx, "/proto.Database/GetValues", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) WatchPrefix(ctx context.Context, in *WatchPrefixRequest, opts ...grpc.CallOption) (*WatchPrefixResponse, error) {
	out := new(WatchPrefixResponse)
	err := grpc.Invoke(ctx, "/proto.Database/WatchPrefix", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Database service

type DatabaseServer interface {
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	GetValues(context.Context, *GetValuesRequest) (*GetValuesResponse, error)
	WatchPrefix(context.Context, *WatchPrefixRequest) (*WatchPrefixResponse, error)
}

func RegisterDatabaseServer(s *grpc.Server, srv DatabaseServer) {
	s.RegisterService(&_Database_serviceDesc, srv)
}

func _Database_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Database/Configure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_GetValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).GetValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Database/GetValues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).GetValues(ctx, req.(*GetValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_WatchPrefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatchPrefixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).WatchPrefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Database/WatchPrefix",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).WatchPrefix(ctx, req.(*WatchPrefixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Database_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Database",
	HandlerType: (*DatabaseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Configure",
			Handler:    _Database_Configure_Handler,
		},
		{
			MethodName: "GetValues",
			Handler:    _Database_GetValues_Handler,
		},
		{
			MethodName: "WatchPrefix",
			Handler:    _Database_WatchPrefix_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "database.proto",
}

func init() { proto1.RegisterFile("database.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x4f, 0x83, 0x40,
	0x10, 0xcd, 0x96, 0x42, 0x64, 0x48, 0x0c, 0xdd, 0x36, 0x8a, 0x24, 0x26, 0x04, 0x8d, 0x21, 0x31,
	0xe1, 0x50, 0x2f, 0x7e, 0xa5, 0x17, 0x6b, 0x8c, 0x37, 0xc3, 0x41, 0x8f, 0xcd, 0xb6, 0xdd, 0x2a,
	0xa9, 0x01, 0x64, 0x17, 0x2d, 0x7f, 0xc1, 0xf8, 0xe3, 0xfc, 0x49, 0x86, 0xdd, 0x2d, 0x62, 0xd1,
	0x83, 0x27, 0x76, 0xde, 0xbc, 0x37, 0x33, 0x6f, 0x06, 0xd8, 0x9e, 0x13, 0x4e, 0xa6, 0x84, 0xd1,
	0x30, 0xcb, 0x53, 0x9e, 0x62, 0x5d, 0x7c, 0xfc, 0x77, 0x04, 0xf6, 0x55, 0x9a, 0x2c, 0xe2, 0xc7,
	0x22, 0xa7, 0x11, 0x7d, 0x29, 0x28, 0xe3, 0xf8, 0x02, 0x8c, 0x99, 0xc0, 0x1c, 0xe4, 0x69, 0x81,
	0x35, 0x3c, 0x90, 0x9a, 0x70, 0x93, 0xa8, 0x80, 0xeb, 0x84, 0xe7, 0x65, 0xa4, 0x24, 0xee, 0x19,
	0x58, 0x0d, 0x18, 0xdb, 0xa0, 0x2d, 0x69, 0xe9, 0x20, 0x0f, 0x05, 0x66, 0x54, 0x3d, 0xf1, 0x00,
	0xf4, 0x57, 0xf2, 0x5c, 0x50, 0xa7, 0x23, 0x30, 0x19, 0x9c, 0x77, 0x4e, 0x91, 0xdf, 0x87, 0x5e,
	0xa3, 0x05, 0xcb, 0xd2, 0x84, 0x51, 0xff, 0x08, 0xec, 0x1b, 0xca, 0xef, 0x2b, 0x12, 0x5b, 0x0f,
	0x88, 0xa1, 0xbb, 0xa4, 0x25, 0x13, 0xe3, 0x99, 0x91, 0x78, 0xfb, 0x1f, 0x08, 0x7a, 0x0d, 0xa2,
	0x54, 0xe3, 0x4b, 0x30, 0x44, 0x7d, 0xa6, 0xac, 0x1c, 0x2a, 0x2b, 0x2d, 0x66, 0x28, 0x43, 0xe5,
	0x45, 0x6a, 0x2a, 0x2f, 0x0d, 0xf8, 0x5f, 0x5e, 0x26, 0x80, 0x1f, 0x08, 0x9f, 0x3d, 0xdd, 0xe5,
	0x74, 0x11, 0xaf, 0xd6, 0x83, 0xef, 0x80, 0x91, 0x09, 0x40, 0x15, 0x51, 0x51, 0x6d, 0xa8, 0xf3,
	0x6d, 0x08, 0xef, 0x03, 0xbc, 0x91, 0x98, 0x4f, 0xe2, 0x64, 0x4e, 0x57, 0x8e, 0xe6, 0xa1, 0xa0,
	0x1b, 0x99, 0x15, 0x72, 0x5b, 0x01, 0xfe, 0x31, 0xf4, 0x7f, 0x34, 0x50, 0x86, 0x07, 0xa0, 0x4b,
	0x01, 0x12, 0x02, 0x19, 0x0c, 0x3f, 0x11, 0x6c, 0x8d, 0xd5, 0x0f, 0x80, 0x47, 0x60, 0xd6, 0x6b,
	0xc6, 0xbb, 0x7f, 0xdc, 0xd6, 0x75, 0xda, 0x09, 0xd5, 0x62, 0x04, 0x66, 0xbd, 0xbe, 0x5a, 0xbf,
	0x79, 0xa3, 0x5a, 0xdf, 0xbe, 0xc9, 0x18, 0xac, 0xc6, 0xe4, 0x78, 0x4f, 0x11, 0xdb, 0xeb, 0x72,
	0xdd, 0xdf, 0x52, 0xb2, 0xca, 0xd4, 0x10, 0xa9, 0x93, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8b,
	0x82, 0x87, 0x47, 0xd9, 0x02, 0x00, 0x00,
}
